language: node_js
node_js:
  - "4.1"
  - "4.0"

install:
  - node node_modules/react-tools/bin/jsx ./src ./build
  - npm install -g bower
  - npm install -g grunt-cli
  - npm install && bower install

script: grunt build
